---
title: "IN400: Applied Mathematics & Statistics for Computational Sciences"
subtitle: "M1 Computer Science - Lebanese University - Faculty of Science"
author: Youssef Salman & Mohamad Ghassany
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
    css: style.css
    toc: true
---


## Description

Data Science, more specifically Machine learning, is powered by four critical concepts: Statistics, Linear Algebra, Probability, and Calculus. While statistical concepts are the core part of every model, calculus helps us learn and optimize a model. Linear algebra comes exceptionally handy when we are dealing with a huge dataset and probability helps in predicting the likelihood of events that will be occurring. These are the mathematical concepts that you will encounter in your data science and machine learning career quite frequently.

This course provides a comprehensive introduction to essential mathematical concepts and techniques necessary for understanding and applying machine learning and AI algorithms.

The course syllabus is available here: [IN400-Syllab](./IN400-syllab.pdf){target='_blank'} 

This course was constructed by dr. [Youssef Salman](https://www.linkedin.com/in/youssef-salman-phd-4b064b1a2/?isSelfProfile=false){target='_blank'} . 


It is taught by Dr. Salman, dr. [M.Z.Ghassany](https://www.mghassany.com/){target='_blank'}  and dr. M.A.Ghassany. 

## Chapter 1: Introduction

| Ressource  | File |
| ------------- | ------------- |
| Presentation | [📖](./Ch1/pres_ch1.pdf) |
| Mathematical Foundations | [📖](./Ch1/Mathematical_Foundations.pdf) |
| Python Libraries | [Nympy](./Ch1/numpy.pdf) & [Scipy](../Ch1/scipy.pdf) |
| Lab | [✍️](./Ch1/TP1.pdf) |



## Chapter 2: Linear Algebra for Machine Learning

| Ressource  | File |
| ------------- | ------------- |
| Presentation | [📖](./Ch2/Ch2_Pres.pdf) |
| Chapter | [📖](./Ch2/chapter2.pdf) |
| Lab | [✍️](./Ch2/TP2.pdf) |

