---
title: "Mathematical Concepts for AI"
subtitle: "Master AIDE"
author: Mohamad Ghassany
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
    css: style.css
    toc: true
---


## Description

Data Science, more specifically Machine learning, is powered by four critical concepts: Statistics, Linear Algebra, Probability, and Calculus. While statistical concepts are the core part of every model, calculus helps us learn and optimize a model. Linear algebra comes exceptionally handy when we are dealing with a huge dataset and probability helps in predicting the likelihood of events that will be occurring. These are the mathematical concepts that you will encounter in your data science and machine learning career quite frequently.

This course provides a comprehensive introduction to essential mathematical concepts and techniques necessary for understanding and applying machine learning and AI algorithms.


## Linear Algebra

**Ressources and slides** 

| Ressource  | File |
| ------------- | ------------- |
| Linear algebra slides | [pdf](slides/Linear-algebra.pdf) |
| Dimensionality reduction (PCA) | [pdf](slides/dimensionality-reduction.pdf) |
| Slides from DeepLearning.AI Mathematics for ML and Data Science Specialization | [zip](slides/Maths-for-ML-LA.zip) |
| Book "Linear Algebra Done Right" | [pdf](https://linear.axler.net/LADR4e.pdf) |

**Labs** 


| Content  | Files |
| ------------- | ------------- |
| Introduction to numpy arrays <br/> Linear systems as matrices <br/> Solving linear systems | [Lab1](./Labs/LA/Lab1.zip)  |
| Gaussian Elimination  | [Lab2](./Labs/LA/Lab2.zip)  |
| Vector operations <br/> Matrix multiplication <br/> Linear transformations | [Lab3](./Labs/LA/Lab3.zip)  |
| Linear Transformations and Neural Networks | [Lab4](./Labs/LA/Lab4.zip)  |
| Eigenvalues and eigenvectors | [Lab5](./Labs/LA/Lab5.zip) and [Lab-PCA](https://www.mghassany.com/courses/MLEfreiS8/Lab-Dim-Red.html)  |

Credits: labs are from DeepLearning.AI Mathematics for ML and Data Science Specialization.




## Probability and Statistics

For preliminary preparation you can refer to this course: [Mathematics for Data Science](https://www.mghassany.com/courses/MDSEfreiS7/index.html)

| Topic                                                                                                     | Slides                                                                                          | Exercises sheet |
|:-----------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------|-----------------|
| Introduction to Probability theory, <br> Random Variables                                                 | [📖](https://www.mghassany.com/courses/MDSEfreiS7/Slides/Lecture1_random_variables.pdf)                                                      | [✍️](https://www.mghassany.com/courses/MDSEfreiS7/td1.html)  |
| Continuous random variables, <br> Introduction to Statistical Inference, <br> Sampling and Limit Theorems | [📖](https://www.mghassany.com/courses/MDSEfreiS7/Slides/Lecture2_continuous_random_variables.pdf) and [📖](Slides/Lecture2bis_sampling.pdf) | [✍️](https://www.mghassany.com/courses/MDSEfreiS7/td2.html)  |
| Point Estimation                                                                                          | [📖](https://www.mghassany.com/courses/MDSEfreiS7/Slides/Lecture3_point_estimation.pdf)                                                      | [✍️](https://www.mghassany.com/courses/MDSEfreiS7/td3.html)  |
| Confidence Intervals                                                                                      | [📖](https://www.mghassany.com/courses/MDSEfreiS7/Slides/Lecture4_confidence_intervals.pdf)                                                  | [✍️](https://www.mghassany.com/courses/MDSEfreiS7/td4.html)  |
| Hypothesis Tests: one sample                                                                              | [📖](https://www.mghassany.com/courses/MDSEfreiS7/Slides/Lecture5_statistical_Tests_1sample.pdf)                                             | [✍️](https://www.mghassany.com/courses/MDSEfreiS7/td5.html)  |
| Hypothesis Tests: two samples                                                                             | [📖](https://www.mghassany.com/courses/MDSEfreiS7/Slides/Lecture6_Statistical_Tests_2samples.pdf)                                            | [✍️](https://www.mghassany.com/courses/MDSEfreiS7/td6.html)  |
| Chi-Squared Tests                                                                               | [📖](https://www.mghassany.com/courses/MDSEfreiS7/Slides/Lecture7_Chi_Squared_tests.pdf)                                                      | [✍️](https://www.mghassany.com/courses/MDSEfreiS7/td7.html)  |




## Calculus and  Optimization

