project:
  type: website

website:
  title: "EFREI Paris -- PGE Blog"
  site-url: https://www.mghassany.com/efreiblog/blogdata
  description: "This is EFREI PGE Blog."
  navbar:
    right:
      - text: Pôle Data
        href: blogdata.qmd 
      - text: Pôle Cyber
        href: blogcyber.qmd 
      - icon: github
        href: https://github.com/
      - icon: rss
        href: blogdata.xml
format:
  html:
    theme: cosmo
    css: styles.css



